---
apiVersion: v1
kind: Service
metadata:
  name: exc2-svc
  labels:
    app: exc2-app
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: exc2-app
  type: ClusterIP